### PR TITLE
Parallel/ multiple read() access for Webots Camera

### LINKED ISSUE #1047: Webots camera does not support parallel access
Even when disabling the openvino stuff, webots does not work properly.
The [camera implementation](https://github.com/HULKs/hulk/blob/main/crates/hulk_webots/src/camera.rs) for `hulk_webots` does not support the parallel access feature implemented in #564.

This results in the setup node crashing and returning an error.
But because of a bug in the communication server, the symptom is actually the simulation not advancing and communication using 100% of one CPU core, see #1046,

### PR DESCRIPTION
**Pull request by tuxbotix**
## Why? What?

As described in #1047 , the issue boils down to the way how the webots cameras are read from.

Compared to the `hulks_nao` camera, there isn't a queue of images, but a `Option<Vec<u8>>`. When `read()` is called, this option is emptied by calling `take()` resulting in the next `read()` call triggering an error (due to empty option) that happens *before*  `update_image()` is called.

Possible Solutions:
1. Clone the buffer and take -> no need to change the condition variable's announcing mechanism. Also the second cycler will get the same image (i.e. object detection)
2. Switch to `tokio` based approach done in #564 but I think this is overkill for the job.
3. Change how the condition variable is notified, use `notify_once` instead of `notify_all` -> two different cycles calling `read()` on same camera will get images from other times as things are now deferred. Additionally, the second cycler will wait for the next image.

This PR took the option 1, the simplest. IMO the possible drawbacks are lesser than the additional complexities we introduce from other methods.

Fixes #1047, #1034

## How to Test

Things should run on Webots fine, can test with Twix, etc.
Users with OpenVino errors should refer to #1068 and ensure their installation is done properly.

### CODE REVIEW

File: crates/hulk_webots/src/camera.rs [hunk 1]
```diff
@@ -67,8 +67,9 @@ impl Camera {
             let mut bgra_buffer = self.buffer.lock();
             self.buffer_updated.wait(&mut bgra_buffer);
             bgra_buffer
+                .clone()
```
Comment (oleflb) [inline crates/hulk_webots/src/camera.rs:70]: This behavior is different compared to the robotics implementation. I'd be fine merging this anyway and opening an issue that we should make the implementations similar. However the fix in this PR would allow people to use webots again. What do you think of this @schmidma @knoellle

**Review by oleflb — COMMENTED** [review]
Waiting for feedback

File: crates/hulk_webots/src/camera.rs (hunk 1 above)
Comment (tuxbotix) [reply crates/hulk_webots/src/camera.rs:70]: I was tempted to use the tokio sender/ receiver pattern, but I wanted to get it working in the first place to work on another PR.

Comment (schmidma) [reply crates/hulk_webots/src/camera.rs:70]: Please open an issue with a proper description of the problem, then I'm totally fine with this quick fix to get webots running again

**Comment by oleflb** [comment]
Someone with webots please test, opened issue in #1073 to describe the issue with this PR. If webots works with this PR, we can merge it

File: crates/hulk_webots/src/camera.rs (hunk 1 above)
Comment (oleflb) [reply crates/hulk_webots/src/camera.rs:70]: #1073

**Comment by tuxbotix** [comment]
I'm already using webots with this :wink: , of course, if secondary verification is needed, we need to wait for a volunteer ^_^ 
image
