### PR TITLE
Fix directed cathesis is not a real number

### LINKED ISSUE #1038: Directed cathesis is None
... a panic that occurred several times during test games.

There was the suspicion that this correlates to planning a path during standing up.

### PR DESCRIPTION
**Pull request by julianschuler**
## Why? What?

This PR ensures that destinations exactly in the center of an obstacle are not moved since the movement direction in this case is zero.

Fixes #1038.

## ToDo / Known Issues

None.

## Ideas for Next Iterations (Not This PR)

Investigate further why behavior request a destination in exactly the center of an obstacle.

## How to Test

Switch to `thagonduarte/directed-cathesis-in-behavior-sim`, run the behavior simulator and observe the panic.

```
pepsi run --target behavior_simulator -- run tests/behavior/ball_intercept.lua
```

Cherry pick the commit of this PR and observe how the panic is fixed.

### CODE REVIEW

File: crates/control/src/path_planner.rs [hunk 1]
```diff
@@ -278,8 +278,10 @@ impl PathPlanner {
             .min_by_key(|circle| NotNan::new(circle.center.coords().norm_squared()).unwrap());
         if let Some(circle) = closest_circle {
             let to_destination = destination - circle.center;
-            let safety_radius = circle.radius * 1.1;
-            destination += to_destination.normalize() * (safety_radius - to_destination.norm());
+            if to_destination.norm_squared() >= f32::EPSILON {
+                let safety_radius = circle.radius * 1.1;
+                destination += to_destination.normalize() * (safety_radius - to_destination.norm());
```
Comment (schmidma) [inline crates/control/src/path_planner.rs:283]: Use https://docs.rs/nalgebra/latest/nalgebra/base/struct.Matrix.html#method.try_normalize here

Comment (julianschuler) [reply crates/control/src/path_planner.rs]: Thanks, done.

**Review by schmidma — APPROVED** [review]
