### PR TITLE
Use parry2d convex hull computation

### LINKED ISSUE #1948: Postgame: Crash while Walking
During the testgame today, robot with playernumber 4 crashed during walking, maybe due to a catching step?

### LINKED ISSUE #1964: unshittify convex hull algorithm

### PR DESCRIPTION
**Pull request by oleflb**
## Why? What?

Replaces our gift wrapping convex hull implementation with the quickhull implementation by parry2d.

Fixes #1964 Fixes #1948

## ToDo / Known Issues

- [x] The implementation crashes when less than 3 points are given to it

## Ideas for Next Iterations (Not This PR)

*If there are some improvements that could be done in a next iteration, describe them here.*

## How to Test

* pepsi test
* look at limbs
* look at zmp catching steps

### CODE REVIEW

File: crates/geometry/src/convex_hull.rs [hunk 1]
```diff
@@ -1,56 +1,44 @@
...
-            break;
-        }
+pub fn reduce_to_convex_hull<Frame>(points: &[Point2<Frame>]) -> Vec<Point2<Frame>> {
+    if points.len() < 3 {
+        return points.to_vec();
     }
-    convex_hull
+
+    // SAFETY: linear_algebra::Point2 has repr(transparent) and is guaranteed to have the same memory layout as nalgebra::Point2
+    let points: &[_] = unsafe { std::mem::transmute(points) };
```
Comment (schmidma) [inline crates/geometry/src/convex_hull.rs:10]: use `transmute` above:


```suggestion
    let points: &[_] = unsafe { transmute(points) };
```

File: crates/geometry/Cargo.toml [hunk 2]
```diff
@@ -11,8 +11,11 @@ approx_derive = { workspace = true }
 linear_algebra = { workspace = true }
 nalgebra = { workspace = true }
 num-traits = { workspace = true }
+parry2d = { workspace = true }
 path_serde = { workspace = true }
 serde = { workspace = true }
 
+
```
Comment (schmidma) [inline crates/geometry/Cargo.toml:18]: remove unnecessary empty line

File: crates/linear_algebra/src/framed.rs [hunk 3]
```diff
@@ -11,6 +11,7 @@ use std::{
 };
 
 #[derive(Debug)]
+#[repr(transparent)]
```
Comment (schmidma) [inline crates/linear_algebra/src/framed.rs:14]: leave a comment here, explaining why it is here to ensure that this is not removed in the future

**Review by schmidma — CHANGES_REQUESTED** [review]
