### PR TITLE
Fix path oscillations

### LINKED ISSUE #264: Prevent oscillations in path when walk target behind obstacle.
When there is an obstacle right between the walk target and the robot, the planned path can oscillate between passing the obstacle on either side.
This causes the robot to jockel in place.

### PR DESCRIPTION
**Pull request by julianschuler**
## Introduced Changes

This PR introduces a `rotation_penalty_factor` to the path planner to reduce flipping between two similar paths, which can cause jockeling.
It also adds a scenario file for testing different values of `rotation_penalty_factor`.

Fixes #264.

## ToDo / Known Issues

None.

## Ideas for Next Iterations (Not This PR)

None.

## How to Test

This is really hard to test outside of the behavior simulator, so I would suggest to watch closely within a game.

### CODE REVIEW

File: tests/behavior/oscillating_obstacle.lua [hunk 1]
```diff
@@ -0,0 +1,36 @@
...
+function on_cycle()
+  if state.cycle_count == 100 then
+    state.ball = {
+      position = { 1.0, 0.0 },
+      velocity = { 0.0, 0.0 },
+    }
+    set_robot_pose(2, { -1.0, 0 }, 0)
+
+    create_obstacle(2, { 0.1, 0.0 }, 0.3)
+  end
```
Comment (MaikRe) [inline tests/behavior/oscillating_obstacle.lua:22]: I suggest doing this in frame 1 to prevent unnecessary robot teleport after start.

**Review by MaikRe — CHANGES_REQUESTED** [review]

**Comment by MaikRe** [comment]
image
Do you have any idea why this happens? It only appears for one from in the lua file but seems high suspicious to me.

**Comment by julianschuler** [comment]
> image Do you have any idea why this happens? It only appears for 9 frames (913-921) in the lua file but seems highly suspicious to me.

The wierd target position is from the fact that there is no ball filter in the behavior simulator and the robot directly forgets about the ball after it leaves its field of view. Due to its rotation the longer path is preferred. Thus the `rotation_penalty_factor` probably has to be reduced.

File: tests/behavior/oscillating_obstacle.lua (hunk 1 above)
Comment (julianschuler) [reply tests/behavior/oscillating_obstacle.lua]: Thanks, done.

File: crates/control/src/behavior/node.rs [hunk 2]
```diff
@@ -38,11 +40,11 @@ pub struct CreationContext {
 pub struct CycleContext {
     pub path_obstacles: AdditionalOutput<Vec<PathObstacle>, "path_obstacles">,
     pub active_action: AdditionalOutput<Action, "active_action">,
+    pub time_to_reach_obstacles: AdditionalOutput<Vec<PathObstacle>, "time_to_reach_obstacles">,
```
Comment (knoellle) [inline crates/control/src/behavior/node.rs:43]: What is the point of this additional output?

**Review by knoellle — CHANGES_REQUESTED** [review]

File: crates/control/src/behavior/node.rs (hunk 2 above)
Comment (julianschuler) [reply crates/control/src/behavior/node.rs:43]: This was moved out of `dribble_path_planner` since it is not a node anymore. @MaikRe why did you need this?

File: crates/control/src/dribble_path_planner.rs [hunk 3]
```diff
@@ -1,110 +1,70 @@
...
+pub fn plan(
+    walk_path_planner: &WalkPathPlanner,
+    world_state: &WorldState,
+    dribbling_parameters: &Dribbling,
+    path_obstacles_output: &mut AdditionalOutput<Vec<PathObstacle>>,
+) -> Option<Vec<PathSegment>> {
+    let Some(kick_decisions) = world_state.kick_decisions.as_ref() else { return None };
+    let Some(best_kick_decision) = kick_decisions.first() else { return None };
+    let Some(ball) = world_state.ball else { return None };
+    let Some(robot_to_field) = world_state.robot.robot_to_field else { return None };
```
[the remark this answers is not in the document]
Comment (julianschuler) [reply crates/control/src/dribble_path_planner.rs]: Thanks for the hint, done.

File: crates/control/src/path_planner.rs [hunk 4]
```diff
@@ -34,9 +34,50 @@ pub struct PathPlanner {
...
     pub obstacles: Vec<PathObstacle>,
+    pub last_path_direction: Option<UnitComplex<f32>>,
+    pub rotation_penalty_factor: f32,
 }
 
 impl PathPlanner {
+    pub fn from_last_motion(
+        last_motion_command: &MotionCommand,
+        rotation_penalty_factor: f32,
+    ) -> Self {
```
[the remark this answers is not in the document]
Comment (julianschuler) [reply crates/control/src/path_planner.rs]: Thanks, done.

File: crates/control/src/behavior/node.rs (hunk 2 above)
Comment (knoellle) [reply crates/control/src/behavior/node.rs:43]: More specifically, the `path_obstacles` additional output is currently empty when the robot dribbles.
The dribble action used to fill this output but now that the dribble path is precalculated, it only fills the `time_to_reach_obstacles` (which might not be the best name anyways).
Are there cases where we'd want to have the dribble path obstacles separately even though the robot does something else?
If not, I'd say we should merge the two, otherwise, the dribble obstacles should be copied to the path obstacles when the robot is executing the dribble action.

Comment (julianschuler) [reply crates/control/src/behavior/node.rs]: Good point. I renamed the `time_to_reach_obstacles` to `dribble_path_obstacles` and filled the `path_obstacles` accordingly.

**Review by MaikRe — APPROVED** [review]

**Review by knoellle — APPROVED** [review]
LGTM
