### PR TITLE
Penalty shootout keeper improvements

### LINKED ISSUE #477: Penalty shootout behaviour is buggy/ weird
We did a quick test of the keeper; 
- the transition to "arms up" pose takes some time (since command from GC).
    - The head wobbles like in a very fast lookaround and do something weird.
- The motion is triggered *okay* under some conditions 
    - might be due to incorrect vision params for the field
- ~The side jumps are rather harsh and almost sounds like bones cracking, Nao Devils got us some tips~ -> #482 
- The jump is triggered just by a static ball , etc. It is way too sensntive.

TODOs:
- [x] check if we can tune the trigger happiness like the old C++ keeper
    - Old implementation for reference: https://github.com/HULKs/nao/blob/cpp/src/Brain/Behavior/PenaltyKeeperActionProvider.cpp
    - ^ Turns out that we already have something similar, but without checking any velocity stuff
- [ ] The current implementation relies on the position of the ball. this means it will jump for a static ball as well. Decide if we should use a minimum velocity to cause a trigger.
- ~see if we can find a way to improve the fanciness of kicking~ -> #483 
- [ ] add a way to disable jumping motions for testing (just do a look at)

### PR DESCRIPTION
**Pull request by MaikRe**
## Why? What?

- Correctly set location during set phase of penalty shootout to prevent robot randomely jerking head because localization keeps generating alternating field sides
- Turn off active vision during penalty shootout to prevent keeper looking up and down between ball and 1m in front of self
- Use whistle in set ball position to determine penalty shot direction to counter for poor camera matrix
- Use a y distance threshold other than zero, specifically require a distance to be greater than one where the linear projection of the ball would lead to it rolling past the robots feet. If the threshold is not met it probably makes more sense to remain standing

Mitigates #997 and #546
Fixes #477 

## Ideas for Next Iterations (Not This PR)

The y direction threshold can be further adapted to accommodate for a wide stance once implemented

## How to Test

Do penalty shootout I guess. A slightly off camera matrix should no longer lead to immediate jumping. And if the ball rolls straight at the robot he should remain standing.

### CODE REVIEW

**Comment by MaikRe** [comment]
@knoellle  I could not reproduce the weird drift issue we had yesterday, even when using the same robot and following the same game states that we had use, including undos. 
Would need to be looked at more, for now I suggest merging this PR

File: crates/control/src/penalty_shot_direction_estimation.rs [hunk 1]
```diff
@@ -53,28 +59,46 @@ impl PenaltyShotDirectionEstimation {
...
                 self.last_shot_direction = PenaltyShotDirection::NotMoving;
+                self.placed_ball_position = Some(context.ball_position.position);
                 Ok(MainOutputs::default())
             }
             (PrimaryState::Playing, GamePhase::PenaltyShootout { .. }, ..)
             | (PrimaryState::Playing, _, Some(SubState::PenaltyKick), Team::Opponent) => {
+                let penalty_marker_position_in_ground = context.ground_to_field.inverse()
+                    * FieldDimensions::penalty_spot(
+                        context.field_dimensions,
+                        types::field_dimensions::Half::Own,
```
Comment (knoellle) [inline crates/control/src/penalty_shot_direction_estimation.rs:70]: replace qualified path with use

**Review by knoellle — APPROVED** [review]
Held good to me
